const { strict: assert } = require('node:assert');
const { existsSync, readFileSync } = require('node:fs');
const { resolve } = require('node:path');
const { test } = require('node:test');

const root = resolve(__dirname, '..');

function readRepoFile(path: string): string {
  return readFileSync(resolve(root, path), 'utf8');
}

test('editor interaction module exposes a key-stream runner', () => {
  const source = readRepoFile('src/editor-interaction.asm');

  assert.match(source, /^@EditorRunKeys:/m);
  assert.match(source, /^@EditorRunModifiedKey:/m);
  assert.match(source, /^@EditorRunLive:/m);
  assert.match(source, /^@EditorCursorReset:/m);
  assert.match(source, /^@EditorCursorResetState:/m);
  assert.match(source, /^@EditorRenderCursor:/m);
  assert.match(source, /^@EditorHideCursor:/m);
  assert.match(source, /^@EditorEnsureCursorVisible:/m);
  assert.match(source, /^@EditorEnsureCursorVisibleColumn:/m);
  assert.match(source, /^@EditorKeyRenderViewport:/m);
  assert.match(source, /^@EditorInvalidateCursorOverlay:/m);
  assert.match(source, /^@EditorKeyRenderCursorRowMarkers:/m);
  assert.match(source, /^@EditorActionFromKey:/m);
  assert.match(source, /^@EditorInsertChar:/m);
  assert.match(source, /^@EditorBackspaceChar:/m);
  assert.match(source, /^@EditorDeleteChar:/m);
  assert.match(source, /^@EditorSplitLine:/m);
  assert.match(source, /^@EditorJoinPreviousLine:/m);
  assert.match(source, /^@EditorJoinPreviousPageLine:/m);
  assert.match(source, /^@EditorKeyReadRecordLength:/m);
  assert.match(source, /^@EditorKeyWriteRecordLength:/m);
  assert.match(source, /^@EditorMarkDirty:/m);
  assert.match(source, /^@EditorKeyRenderCurrentLineDirty:/m);
  assert.match(source, /^@EditorPromptAskYesNo:/m);
  assert.match(source, /^@EditorPromptDispatch:/m);
  assert.match(source, /^@EditorModifiedCommandFromKey:/m);
  assert.match(source, /^@EditorShouldIgnoreModifiedPrintable:/m);
  assert.match(source, /^@EditorKeyShowStatus:/m);
  assert.match(source, /TECM8_EDITOR_KEY_QUIT\s+\.equ\s+17/);
  assert.match(source, /TECM8_EDITOR_KEY_RESTORE\s+\.equ\s+18/);
  assert.match(source, /TECM8_EDITOR_KEY_SAVE\s+\.equ\s+19/);
  assert.match(source, /TECM8_EDITOR_KEY_ALT_QUIT\s+\.equ\s+24/);
  assert.match(source, /TECM8_EDITOR_KEY_ARROW_UP\s+\.equ\s+0x03/);
  assert.match(source, /TECM8_EDITOR_KEY_ARROW_DOWN\s+\.equ\s+0x04/);
  assert.match(source, /TECM8_EDITOR_KEY_ARROW_LEFT\s+\.equ\s+0x05/);
  assert.match(source, /TECM8_EDITOR_KEY_ARROW_RIGHT\s+\.equ\s+0x06/);
  assert.match(source, /TECM8_EDITOR_KEY_MOD_CTRL\s+\.equ\s+0x02/);
  assert.match(source, /TECM8_EDITOR_KEY_MOD_ALT\s+\.equ\s+0x08/);
  assert.match(source, /TECM8_EDITOR_KEY_MOD_PAGE\s+\.equ\s+0x0A/);
  assert.match(source, /TECM8_EDITOR_KEY_ESCAPE\s+\.equ\s+27/);
  assert.match(source, /CP\s+TECM8_EDITOR_KEY_ALT_QUIT\n\s+JP\s+Z,EditorKeyQuit/);
  assert.match(source, /TECM8_EDITOR_ACTION_CURSOR_LEFT\s+\.equ\s+3/);
  assert.match(source, /TECM8_EDITOR_ACTION_CURSOR_DOWN\s+\.equ\s+4/);
  assert.match(source, /TECM8_EDITOR_ACTION_CURSOR_UP\s+\.equ\s+5/);
  assert.match(source, /TECM8_EDITOR_ACTION_CURSOR_RIGHT\s+\.equ\s+6/);
  assert.doesNotMatch(source, /TECM8_EDITOR_PROOF_KEY_CURSOR_LEFT_LOWER/);
  assert.doesNotMatch(source, /TECM8_EDITOR_PROOF_KEY_CURSOR_DOWN_LOWER/);
  assert.doesNotMatch(source, /TECM8_EDITOR_PROOF_KEY_CURSOR_UP_LOWER/);
  assert.doesNotMatch(source, /TECM8_EDITOR_PROOF_KEY_CURSOR_RIGHT_LOWER/);
  assert.doesNotMatch(source, /TECM8_EDITOR_PROOF_KEY_PAGE_/);
  assert.match(source, /TECM8_EDITOR_PROMPT_RESULT_YES\s+\.equ\s+1/);
  assert.match(source, /TECM8_EDITOR_PROMPT_RESULT_NO\s+\.equ\s+2/);
  assert.match(source, /;!\s+in\s+HL\n;!\s+out\s+A,carry\n;!\s+clobbers\s+A,BC,DE,HL,zero,sign,parity,halfCarry\n@EditorRunKeys:/);
  assert.match(source, /;!\s+in\s+A,B\n;!\s+out\s+A,carry\n;!\s+clobbers\s+A,BC,DE,HL,zero,sign,parity,halfCarry\n@EditorRunModifiedKey:/);
  assert.match(source, /;!\s+in\s+A\n;!\s+out\s+A,carry\n;!\s+clobbers\s+A,zero,sign,parity,halfCarry\n@EditorActionFromKey:/);
  assert.match(source, /;!\s+in\s+A\n;!\s+out\s+A,carry\n;!\s+clobbers\s+A,BC,DE,HL,zero,sign,parity,halfCarry\n@EditorInsertChar:/);
  assert.match(source, /CALL\s+EditorPageDown/);
  assert.match(source, /CALL\s+EditorPageUp/);
  assert.match(source, /CALL\s+EditorSaveCurrentPage/);
  assert.match(source, /CALL\s+EditorPromptHandleKey/);
  assert.match(source, /CALL\s+EditorHideCursor/);
  assert.match(source, /JP\s+EditorViewportRenderStatusOverlay/);
  assert.match(source, /JP\s+EditorViewportRestoreStatusRow/);
  assert.match(source, /CALL\s+EditorLoadCurrentBackupWindow/);
  assert.match(source, /CALL\s+EditorActionFromKey/);
  assert.match(source, /CALL\s+BiosInputPollKey/);
  assert.match(source, /XOR\s+A\n\s+LD\s+\(EditorKeyStreamModifier\),A\n\s+LD\s+\(EditorInsertMode\),A/);
  assert.match(source, /CALL\s+BiosInputPollKey\n\s+JR\s+NC,EditorLiveIdle\n\s+CALL\s+EditorRunModifiedKey/);
  assert.match(source, /@EditorRunModifiedKey:\n\s+LD\s+\(EditorLiveKeyBuffer\),A\n\s+LD\s+A,B\n\s+LD\s+\(EditorKeyStreamModifier\),A/);
  assert.doesNotMatch(source, /CALL\s+EditorRunKeys\n\s+RET\s+C\n\s+CALL\s+GlcdTileFlushFull/);
  assert.doesNotMatch(source, /CALL\s+EditorRenderCursor\n\s+RET\s+C\n\s+CALL\s+GlcdTileFlushFull/);
  assert.match(source, /CALL\s+GlcdTileFlushFull/);
  assert.match(source, /EditorDispatchAction:/);
  assert.match(source, /CP\s+TECM8_EDITOR_KEY_ARROW_UP\n\s+JR\s+Z,EditorActionArrowUp/);
  assert.match(source, /CP\s+TECM8_EDITOR_KEY_ARROW_DOWN\n\s+JR\s+Z,EditorActionArrowDown/);
  assert.match(source, /EditorActionArrowUp:\n\s+LD\s+A,\(EditorPendingModifier\)\n\s+AND\s+TECM8_EDITOR_KEY_MOD_PAGE\n\s+JR\s+NZ,EditorActionPageUp/);
  assert.match(source, /EditorActionArrowDown:\n\s+LD\s+A,\(EditorPendingModifier\)\n\s+AND\s+TECM8_EDITOR_KEY_MOD_PAGE\n\s+JR\s+NZ,EditorActionPageDown/);
  assert.match(source, /CP\s+TECM8_EDITOR_ACTION_CURSOR_LEFT\n\s+JP\s+Z,EditorKeyCursorLeft/);
  assert.doesNotMatch(source, /CP\s+TECM8_EDITOR_PROOF_KEY_CURSOR_LEFT_LOWER/);
  assert.doesNotMatch(source, /CP\s+TECM8_EDITOR_PROOF_KEY_[A-Z_]+\n\s+JP\s+Z,EditorKey/);
  assert.doesNotMatch(source, /EditorActionPageDownLower/);
  assert.match(source, /CALL\s+DisplayRenderCursorCell/);
  assert.match(source, /CALL\s+DisplayEraseCursorCell/);
  assert.match(source, /CALL\s+DisplayRenderCursorCell[\s\S]*?LD\s+A,\(EditorCursorVisibleCol\)\n\s+LD\s+\(EditorCursorRenderedCol\),A/);
  assert.match(source, /@EditorInvalidateCursorOverlay:\n\s+XOR\s+A\n\s+LD\s+\(EditorCursorRendered\),A\n\s+RET/);
  assert.match(source, /CALL\s+EditorRenderPageBuffer/);
  assert.match(source, /CALL\s+EditorViewportRenderRecordRow/);
  assert.match(source, /EditorKeyInsertPrintable:[\s\S]*?CALL\s+EditorKeyRenderCurrentLineDirty/);
  assert.match(source, /EditorKeyDelete:[\s\S]*?CALL\s+EditorKeyRenderCurrentLineDirty/);
  assert.match(source, /EditorKeyBackspaceJoin:[\s\S]*?CALL\s+EditorKeyRenderDirty/);
  assert.match(source, /EditorKeyDone:\n\s+LD\s+A,\(EditorPromptActive\)\n\s+OR\s+A\n\s+JR\s+NZ,EditorKeyDoneNoCursor/);
  assert.match(source, /EditorCursorRow:\n\s+\.db\s+0/);
  assert.match(source, /EditorCursorVisibleRow:\n\s+\.db\s+0/);
  assert.match(source, /EditorCursorVisibleCol:\n\s+\.db\s+0/);
  assert.match(source, /EditorCursorCol:\n\s+\.db\s+0/);
  assert.match(source, /EditorCursorRendered:\n\s+\.db\s+0/);
  assert.match(source, /LD\s+\(EditorCursorRow\),A\n\s+LD\s+\(EditorCursorVisibleRow\),A\n\s+LD\s+\(EditorCursorVisibleCol\),A\n\s+LD\s+\(EditorNavCurrentRow\),A\n\s+LD\s+\(EditorCursorCol\),A[\s\S]*?CALL\s+EditorNavResetViewport/);
  assert.match(source, /CALL\s+EditorViewportSetCurrentRow/);
  assert.match(source, /^@EditorKeyRenderCursorRowMarkers:/m);
  assert.match(source, /JP\s+EditorKeyRenderCursorRowMarkers/);
  assert.match(source, /CALL\s+EditorModifiedCommandFromKey\n\s+RET\s+C\n\s+OR\s+A\n\s+JP\s+NZ,EditorDispatchModifiedCommand/);
  assert.match(source, /EditorModifiedCommandFromKey:[\s\S]*?AND\s+TECM8_EDITOR_KEY_MOD_PAGE/);
  assert.match(source, /CP\s+"s"\n\s+JR\s+Z,EditorModifiedCommandSave/);
  assert.match(source, /CP\s+"S"\n\s+JR\s+Z,EditorModifiedCommandSave/);
  assert.match(source, /CP\s+"x"\n\s+JR\s+Z,EditorModifiedCommandAltQuit/);
  assert.match(source, /CP\s+"X"\n\s+JR\s+Z,EditorModifiedCommandAltQuit/);
  assert.match(source, /CP\s+"q"\n\s+JR\s+Z,EditorModifiedCommandQuit/);
  assert.match(source, /CP\s+"Q"\n\s+JR\s+Z,EditorModifiedCommandQuit/);
  assert.match(source, /EditorDispatchModifiedCommand:[\s\S]*?CP\s+TECM8_EDITOR_KEY_SAVE\n\s+JP\s+Z,EditorKeySave/);
  assert.match(source, /CALL\s+EditorShouldIgnoreModifiedPrintable\n\s+RET\s+C\n\s+OR\s+A\n\s+JP\s+NZ,EditorKeyUnknownModifiedPrintable/);
  assert.match(source, /@EditorShouldIgnoreModifiedPrintable:[\s\S]*?AND\s+TECM8_EDITOR_KEY_MOD_PAGE[\s\S]*?LD\s+A,1\n\s+OR\s+A\n\s+RET/);
  assert.match(source, /EditorKeyUnknownModifiedPrintable:\n\s+LD\s+HL,EditorStatusUnknownKeyText\n\s+CALL\s+EditorKeyShowStatus/);
  assert.match(source, /TECM8_EDITOR_CURSOR_MAX_ROW\s+\.equ\s+15/);
  assert.match(source, /TECM8_EDITOR_CURSOR_VISIBLE_ROWS\s+\.equ\s+10/);
  assert.match(source, /TECM8_EDITOR_CURSOR_MAX_COL\s+\.equ\s+30/);
  assert.match(source, /TECM8_EDITOR_EDIT_RECORD_LENGTH_MASK\s+\.equ\s+0x1F/);
  assert.match(source, /TECM8_EDITOR_EDIT_RECORD_METADATA_MASK\s+\.equ\s+0xE0/);
  assert.match(source, /TECM8_EDITOR_KEY_BACKSPACE\s+\.equ\s+8/);
  assert.match(source, /TECM8_EDITOR_KEY_INSERT_MODE\s+\.equ\s+9/);
  assert.match(source, /TECM8_EDITOR_KEY_NEWLINE\s+\.equ\s+13/);
  assert.match(source, /TECM8_EDITOR_KEY_DELETE\s+\.equ\s+127/);
  assert.match(source, /EditorInsertMode:\n\s+\.db\s+0/);
  assert.match(source, /EditorLiveKeyBuffer:\n\s+\.db\s+0,0/);
  assert.match(source, /EditorKeyStreamModifier:\n\s+\.db\s+0/);
  assert.match(source, /EditorPendingModifier:\n\s+\.db\s+0/);
  assert.match(source, /EditorKeyInsertMode:/);
  assert.match(source, /EditorKeyPrompt:/);
  assert.match(source, /EditorKeyQuit:/);
  assert.match(source, /EditorKeyRestorePrompt:/);
  assert.match(source, /EditorQuitRequested:\n\s+\.db\s+0/);
  assert.match(source, /EditorKeySave:/);
  assert.match(source, /EditorKeySave:\n\s+LD\s+A,\(EditorNavDirty\)\n\s+OR\s+A\n\s+JP\s+Z,EditorKeyCleanSave/);
  assert.match(source, /EditorKeyCleanSave:\n\s+LD\s+HL,EditorStatusCleanText\n\s+CALL\s+EditorKeyShowStatus/);
  assert.match(source, /EditorKeySave:[\s\S]*?CALL\s+EditorHideCursor\n\s+RET\s+C\n\s+CALL\s+EditorSaveCurrentPage/);
  assert.match(source, /EditorKeyPageDown:[\s\S]*?CALL\s+EditorPageDown\n\s+JR\s+C,EditorKeyPageDownErr\n\s+CALL\s+EditorCursorResetState\n\s+CALL\s+EditorInvalidateCursorOverlay/);
  assert.match(source, /EditorKeyPageUp:[\s\S]*?CALL\s+EditorPageUp\n\s+JR\s+C,EditorKeyPageUpErr\n\s+CALL\s+EditorCursorResetState\n\s+CALL\s+EditorInvalidateCursorOverlay/);
  assert.match(source, /EditorKeyDirtyPageBlocked:\n\s+LD\s+HL,EditorStatusSaveFirstText\n\s+CALL\s+EditorKeyShowStatus/);
  assert.match(source, /@EditorKeyShowStatus:\n\s+LD\s+\(EditorStatusTextPtr\),HL\n\s+CALL\s+EditorHideCursor/);
  assert.match(source, /EditorKeyMaybeInsertMode:/);
  assert.match(source, /EditorKeyCursorLeft:/);
  assert.match(source, /EditorKeyCursorDown:/);
  assert.match(source, /EditorKeyCursorUp:/);
  assert.match(source, /EditorKeyCursorDown:[\s\S]*?CALL\s+EditorKeyRenderCursorMove/);
  assert.match(source, /EditorKeyCursorUp:[\s\S]*?CALL\s+EditorKeyRenderCursorMove/);
  assert.match(source, /EditorKeyPageDownErr:[\s\S]*?LD\s+HL,EditorStatusEndText[\s\S]*?CALL\s+EditorKeyShowStatus/);
  assert.match(source, /EditorKeyPageUpErr:[\s\S]*?LD\s+HL,EditorStatusTopText[\s\S]*?CALL\s+EditorKeyShowStatus/);
  assert.match(source, /@EditorEnsureCursorVisible:[\s\S]*?LD\s+A,\(EditorNavViewportTopRow\)[\s\S]*?EditorEnsureCursorScrollDown:/);
  assert.match(source, /@EditorKeyRenderCursorMove:[\s\S]*?CALL\s+EditorEnsureCursorVisible[\s\S]*?JP\s+NZ,EditorKeyRenderViewport/);
  assert.match(source, /EditorKeyPageDown:[\s\S]*?CALL\s+EditorPageDown[\s\S]*?CALL\s+EditorCursorReset/);
  assert.match(source, /EditorKeyPageUp:[\s\S]*?CALL\s+EditorPageUp[\s\S]*?CALL\s+EditorCursorReset/);
  assert.match(source, /@EditorKeyRenderDirty:[\s\S]*?CALL\s+EditorEnsureCursorVisible[\s\S]*?CALL\s+EditorRenderPageBuffer/);
  assert.match(source, /EditorKeyCursorRight:/);
  assert.match(source, /EditorKeyCursorLeft:[\s\S]*?CALL\s+EditorKeyRenderCursorColumnMove/);
  assert.match(source, /EditorKeyCursorRight:[\s\S]*?CALL\s+EditorKeyRenderCursorColumnMove/);
  assert.match(source, /@EditorEnsureCursorVisibleColumn:[\s\S]*?LD\s+A,\(EditorViewportColOffset\)[\s\S]*?EditorEnsureCursorColumnScrollRight:/);
  assert.match(source, /@EditorKeyRenderCursorColumnMove:[\s\S]*?CALL\s+EditorEnsureCursorVisibleColumn[\s\S]*?JP\s+NZ,EditorKeyRenderViewport/);
  assert.match(source, /EditorKeyInsertPrintable:/);
  assert.match(source, /CALL\s+EditorInsertChar/);
  assert.match(source, /CALL\s+EditorInsertChar\n\s+RET\s+C\n\s+OR\s+A\n\s+JP\s+Z,EditorKeyLoop/);
  assert.match(source, /CALL\s+EditorMarkDirty/);
  assert.match(source, /CALL\s+EditorBackspaceChar/);
  assert.match(source, /CALL\s+EditorDeleteChar/);
  assert.match(source, /CALL\s+EditorSplitLine/);
  assert.match(source, /JP\s+Z,EditorJoinPreviousLine/);
  assert.match(source, /@EditorKeyZeroRecordPadding:/);
  assert.match(source, /@EditorKeyReadRecordLength:\n\s+LD\s+A,\(HL\)\n\s+AND\s+TECM8_EDITOR_EDIT_RECORD_LENGTH_MASK/);
  assert.match(source, /@EditorKeyWriteRecordLength:[\s\S]*?AND\s+TECM8_EDITOR_EDIT_RECORD_METADATA_MASK[\s\S]*?OR\s+B\n\s+LD\s+\(HL\),A/);
  assert.match(source, /@EditorSplitPushLastRecordToNextPage:/);
  assert.match(source, /@EditorSplitFinalRow:/);
  assert.match(source, /CALL\s+EditorNavRememberCurrentPage/);
  assert.match(source, /CALL\s+EditorNavSlideNextPageToCurrent/);
  assert.match(source, /EditorNavNextPageBuffer/);
  assert.match(source, /@EditorKeyClearRecord:/);
  assert.match(source, /@EditorJoinPreviousLine:\n\s+LD\s+A,\(EditorCursorCol\)\n\s+OR\s+A\n\s+JP\s+NZ,EditorJoinDone/);
  assert.match(source, /CP\s+TECM8_EDITOR_NAV_ERR_PAGE/);
  assert.match(source, /CP\s+TECM8_EDITOR_INTERACTION_ERR_EOF/);
});

test('editor cross-page join proof is wired into package checks', () => {
  assert.ok(existsSync(resolve(root, 'proofs/display/editor-cross-page-join-proof.asm')));
  const proof = readRepoFile('proofs/display/editor-cross-page-join-proof.asm');
  const runner = readRepoFile('tools/run-editor-viewport-storage-proof.ts');
  const packageJson = readRepoFile('package.json');

  assert.match(proof, /CALL\s+EditorBackspaceChar/);
  assert.match(proof, /EditorNavCachePageBuffer \+ \(15 \* 32\)/);
  assert.match(runner, /verifyEditorCrossPageJoinProof/);
  assert.match(runner, /PREVCUR/);
  assert.match(packageJson, /"proof:display:editor-cross-page-join"/);
  assert.match(packageJson, /proof:display:editor-cross-page-join/);
});

test('shell-launched editor interaction proof is wired into storage proof runner', () => {
  assert.ok(existsSync(resolve(root, 'proofs/display/shell-edit-interaction-proof.asm')));
  const proof = readRepoFile('proofs/display/shell-edit-interaction-proof.asm');
  const runner = readRepoFile('tools/run-editor-viewport-storage-proof.ts');
  const packageJson = readRepoFile('package.json');

  assert.match(proof, /CALL\s+ShellRunEditorSession/);
  assert.match(proof, /\.include\s+"..\/..\/src\/editor-interaction\.asm"/);
  assert.match(proof, /CALL\s+EditorRunModifiedKey/);
  assert.match(proof, /LD\s+A,"W"\n\s+LD\s+B,TECM8_EDITOR_KEY_MOD_ALT\n\s+CALL\s+EditorRunModifiedKey/);
  assert.match(proof, /UnknownModifiedDirty:\n\s+\.db\s+0/);
  assert.match(proof, /LD\s+A,TECM8_EDITOR_KEY_ARROW_DOWN\n\s+LD\s+B,TECM8_EDITOR_KEY_MOD_ALT\n\s+CALL\s+EditorRunModifiedKey/);
  assert.doesNotMatch(proof, /TECM8_EDITOR_PROOF_KEY_PAGE_/);
  assert.match(proof, /NoKeys:\n\s+\.db\s+0/);
  assert.match(proof, /\.db\s+TECM8_EDITOR_KEY_ARROW_LEFT,TECM8_EDITOR_KEY_ARROW_UP/);
  assert.match(proof, /\.db\s+TECM8_EDITOR_KEY_ARROW_RIGHT,TECM8_EDITOR_KEY_ARROW_DOWN/);
  assert.match(proof, /\.db\s+TECM8_EDITOR_KEY_ARROW_LEFT,TECM8_EDITOR_KEY_ARROW_LEFT/);
  assert.match(proof, /\.db\s+9/);
  assert.match(proof, /\.db\s+"dl!"/);
  assert.match(proof, /\.db\s+8/);
  assert.match(proof, /\.db\s+"\?",127,0/);
  assert.match(proof, /EditorKeyLeft:\n\s+\.db\s+TECM8_EDITOR_KEY_ARROW_LEFT,0/);
  assert.match(proof, /EditorKeyRight:\n\s+\.db\s+TECM8_EDITOR_KEY_ARROW_RIGHT,0/);
  assert.match(runner, /shell-edit-interaction-proof/);
  assert.match(runner, /verifyShellEditInteractionProof/);
  assert.match(runner, /verifyShellEditVisibleCursor/);
  assert.match(runner, /EditorCursorRow/);
  assert.match(runner, /EditorCursorCol/);
  assert.match(runner, /EditorCursorVisibleCol/);
  assert.match(runner, /EditorViewportColOffset/);
  assert.match(runner, /expected 8/);
  assert.match(runner, /expected 4/);
  assert.match(runner, /expected 3/);
  assert.match(runner, /expected 1/);
  assert.match(runner, /dl\? LINE 08/);
  assert.match(runner, /mutatedRecord !== 'Adl\? LINE 08'/);
  assert.match(runner, /UnknownModifiedDirty/);
  assert.match(runner, /unknown modified dirty/);
  assert.match(runner, /assertCellMatchesInvertedFont/);
  assert.match(runner, /assertGlcdCellMatchesInvertedFont/);
  assert.doesNotMatch(runner, /previous cursor/);
  assert.match(packageJson, /"proof:display:shell-edit-interaction"/);
  assert.match(packageJson, /proof:display:shell-edit-interaction/);
});

test('editor dirty render proof covers ordinary movement and printable edit paths', () => {
  assert.ok(existsSync(resolve(root, 'proofs/display/editor-dirty-render-proof.asm')));
  const proof = readRepoFile('proofs/display/editor-dirty-render-proof.asm');
  const runner = readRepoFile('tools/run-editor-viewport-storage-proof.ts');
  const packageJson = readRepoFile('package.json');

  assert.match(proof, /CALL\s+ResetRenderCounters/);
  assert.match(proof, /MoveScreenCount:/);
  assert.match(proof, /MovePageCount:/);
  assert.match(proof, /MoveRowCount:/);
  assert.match(proof, /InsertScreenCount:/);
  assert.match(proof, /InsertPageCount:/);
  assert.match(proof, /InsertRowCount:/);
  assert.match(proof, /DisplayRenderScreenCount/);
  assert.match(proof, /EditorRenderPageBufferCount/);
  assert.match(proof, /EditorViewportRenderRecordRowCount/);
  assert.match(runner, /editor-dirty-render-proof/);
  assert.match(runner, /verifyEditorDirtyRenderProof/);
  assert.match(runner, /MoveScreenCount/);
  assert.match(runner, /InsertRowCount/);
  assert.match(runner, /PZ0 LINE 00/);
  assert.match(packageJson, /"proof:display:editor-dirty-render"/);
  assert.match(packageJson, /proof:display:editor-dirty-render/);
});

test('editor row-15 growth proof is wired into package checks', () => {
  assert.ok(existsSync(resolve(root, 'proofs/display/editor-row15-growth-proof.asm')));
  const proof = readRepoFile('proofs/display/editor-row15-growth-proof.asm');
  const runner = readRepoFile('tools/run-editor-viewport-storage-proof.ts');
  const packageJson = readRepoFile('package.json');

  assert.match(proof, /CALL\s+EditorSplitLine/);
  assert.match(proof, /CALL\s+EditorSaveCurrentPage/);
  assert.match(runner, /editor-row15-growth-proof/);
  assert.match(runner, /verifyEditorRow15GrowthProof/);
  assert.match(runner, /stored\.length !== 1024/);
  assert.match(packageJson, /"proof:display:editor-row15-growth"/);
  assert.match(packageJson, /proof:display:editor-row15-growth/);
});

test('editor viewport scroll proof is wired into package checks', () => {
  assert.ok(existsSync(resolve(root, 'proofs/display/editor-viewport-scroll-proof.asm')));
  const proof = readRepoFile('proofs/display/editor-viewport-scroll-proof.asm');
  const runner = readRepoFile('tools/run-editor-viewport-storage-proof.ts');
  const packageJson = readRepoFile('package.json');

  assert.match(proof, /MoveDownToBottom:/);
  assert.match(proof, /CursorRowAfterDown:/);
  assert.match(proof, /TopRowAfterDown:/);
  assert.match(proof, /BottomRowText0:/);
  assert.match(proof, /BottomRowText9:/);
  assert.match(proof, /DirtyAfterUp:/);
  assert.match(runner, /editor-viewport-scroll-proof/);
  assert.match(runner, /verifyEditorViewportScrollProof/);
  assert.match(runner, /CursorRowAfterDown/);
  assert.match(runner, /TopRowAfterDown/);
  assert.match(runner, /BottomRowText0/);
  assert.match(runner, /R0 LINE 15/);
  assert.match(packageJson, /"proof:display:editor-viewport-scroll"/);
  assert.match(packageJson, /proof:display:editor-viewport-scroll/);
});

test('editor horizontal scroll proof is wired into package checks', () => {
  assert.ok(existsSync(resolve(root, 'proofs/display/editor-horizontal-scroll-proof.asm')));
  const proof = readRepoFile('proofs/display/editor-horizontal-scroll-proof.asm');
  const runner = readRepoFile('tools/run-editor-viewport-storage-proof.ts');
  const packageJson = readRepoFile('package.json');

  assert.match(proof, /LongLineKeys:/);
  assert.match(proof, /CursorColAfterInsert:/);
  assert.match(proof, /VisibleColAfterInsert:/);
  assert.match(proof, /ColOffsetAfterInsert:/);
  assert.match(proof, /ShortLinePanKeys:/);
  assert.match(proof, /BackspaceKey:/);
  assert.match(proof, /ShortCursorColAfterBackspace:/);
  assert.match(proof, /ShortVisibleColAfterBackspace:/);
  assert.match(runner, /editor-horizontal-scroll-proof/);
  assert.match(runner, /verifyEditorHorizontalScrollProof/);
  assert.match(runner, /CursorColAfterInsert/);
  assert.match(runner, /ShortCursorColAfterBackspace/);
  assert.match(runner, /ShortVisibleColAfterBackspace/);
  assert.match(runner, /LMNOPQRSTUVWXYZ12345/);
  assert.match(packageJson, /"proof:display:editor-horizontal-scroll"/);
  assert.match(packageJson, /proof:display:editor-horizontal-scroll/);
});

test('editor mutation boundary proof covers fixed-record edge cases', () => {
  assert.ok(existsSync(resolve(root, 'proofs/display/editor-mutation-boundary-proof.asm')));
  const proof = readRepoFile('proofs/display/editor-mutation-boundary-proof.asm');
  const runner = readRepoFile('tools/run-editor-viewport-storage-proof.ts');
  const packageJson = readRepoFile('package.json');

  assert.match(proof, /CALL\s+EditorBackspaceChar/);
  assert.match(proof, /CALL\s+EditorDeleteChar/);
  assert.match(proof, /CALL\s+EditorInsertChar/);
  assert.match(proof, /CALL\s+EditorRunKeys/);
  assert.match(proof, /BoundaryRecord0:\n\s+\.db\s+0/);
  assert.match(proof, /BoundaryRecord1:\n\s+\.db\s+0x7F,"ABCDEFGHIJKLMNOPQRSTUVWXYZ12345"/);
  assert.match(proof, /BoundaryRecord3:\n\s+\.db\s+0xA5,"ABCDE"/);
  assert.match(proof, /BoundaryRecord5:\n\s+\.db\s+0x80/);
  assert.match(proof, /BoundaryReservedKeys:\n\s+\.db\s+9,"dl",0/);
  assert.match(proof, /BoundaryCursorCase1:/);
  assert.match(proof, /BoundaryCursorCase9:/);
  assert.match(proof, /CALL\s+BoundarySaveCursor/);
  assert.match(runner, /editor-mutation-boundary-proof/);
  assert.match(runner, /verifyEditorMutationBoundaryProof/);
  assert.match(runner, /text: 'Z'/);
  assert.match(runner, /text: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ12345'/);
  assert.match(runner, /text: 'ABCDE'/);
  assert.match(runner, /text: 'ABDE'/);
  assert.match(runner, /text: 'XYZ!'/);
  assert.match(runner, /text: 'dl'/);
  assert.match(runner, /expectedLengthBytes/);
  assert.match(runner, /0xa4/);
  assert.match(runner, /0x82/);
  assert.match(runner, /BoundaryCursorCase1', row: 0, col: 0/);
  assert.match(runner, /BoundaryCursorCase4', row: 1, col: 0/);
  assert.match(runner, /BoundaryCursorCase6', row: 2, col: 5/);
  assert.match(runner, /BoundaryCursorCase8', row: 4, col: 4/);
  assert.match(runner, /BoundaryCursorCase9', row: 5, col: 2/);
  assert.match(runner, /BoundaryCursorCase10', row: 15, col: 0/);
  assert.match(runner, /text: 'LE'/);
  assert.match(runner, /text: 'FT'/);
  assert.match(runner, /expected "PUSH"/);
  assert.match(packageJson, /"proof:display:editor-mutation-boundary"/);
  assert.match(packageJson, /proof:display:editor-mutation-boundary/);
});

test('editor line editing proof covers split and join behavior', () => {
  assert.ok(existsSync(resolve(root, 'proofs/display/editor-line-editing-proof.asm')));
  const proof = readRepoFile('proofs/display/editor-line-editing-proof.asm');
  const runner = readRepoFile('tools/run-editor-viewport-storage-proof.ts');
  const packageJson = readRepoFile('package.json');

  assert.match(proof, /CALL\s+EditorSplitLine/);
  assert.match(proof, /CALL\s+EditorBackspaceChar/);
  assert.match(proof, /CALL\s+EditorRunKeys/);
  assert.match(proof, /LineEditNewlineKey:\n\s+\.db\s+13,0/);
  assert.match(proof, /LineEditRecord0:\n\s+\.db\s+5,"HELLO"/);
  assert.match(proof, /LineEditRecord6:\n\s+\.db\s+31,"ABCDEFGHIJKLMNOPQRSTUVWXYZ12345"/);
  assert.match(proof, /LineEditRecordLast:\n\s+\.db\s+4,"LAST"/);
  assert.match(proof, /LineEditCursorCase8:/);
  assert.match(proof, /LineEditCursorCase9:/);
  assert.match(proof, /LineEditCursorCase10:/);
  assert.match(proof, /LineEditResultCase10:/);
  assert.match(runner, /editor-line-editing-proof/);
  assert.match(runner, /verifyEditorLineEditingProof/);
  assert.match(runner, /assertSourceRecordClean/);
  assert.match(runner, /text: 'HELLO'/);
  assert.match(runner, /text: 'NE'/);
  assert.match(runner, /text: 'XT'/);
  assert.match(runner, /text: 'TAIL'/);
  assert.match(runner, /LineEditCursorCase1', row: 1, col: 0/);
  assert.match(runner, /LineEditCursorCase2', row: 0, col: 2/);
  assert.match(runner, /LineEditCursorCase6', row: 15, col: 2/);
  assert.match(runner, /LineEditCursorCase7', row: 2, col: 0/);
  assert.match(runner, /LineEditCursorCase8', row: 1, col: 1/);
  assert.match(runner, /LineEditCursorCase9', row: 0, col: 0/);
  assert.match(runner, /LineEditCursorCase10', row: 15, col: 0/);
  assert.match(runner, /LineEditResultCase6', 'LineEditResultCase9', 'LineEditResultCase10'/);
  assert.match(packageJson, /"proof:display:editor-line-editing"/);
  assert.match(packageJson, /proof:display:editor-line-editing/);
});
